		g3log created log at: Thu Mar 30 13:08:59 2023
		LOG format: [YYYY/MM/DD hh:mm:ss uuu* LEVEL FILE->FUNCTION:LINE] messagen
		(uuu*: microseconds fractions of the seconds value)

2023/03/30 13:08:59 827580	INFO [python_manager.cpp->PythonManager::InitializePython:127]	Initializing Python ... 
2023/03/30 13:08:59 845685	INFO [python_manager.cpp->PythonManager::InitializePython:129]	Initializing Python DONE... 
2023/03/30 13:08:59 845693	INFO [python_manager.cpp->PythonManager::InitNumpy:172]	Init numpy... 
2023/03/30 13:08:59 952744	INFO [python_manager.cpp->PythonManager::InitNumpy:174]	Init numpy DONE... 
2023/03/30 13:12:00 125359	WARNING [python_manager.cpp->PythonManager::CheckForErrors:745]	Error, traceback : ['Traceback (most recent call last):
', '  File "C:/Users/user/OneDrive - ESTACA/Documents/GitHub/ESTADRIVE_23/Main_Perception/PythonBridges\\BlocDistanceArret.py", line 74, in Dynamic
    self.add_output("CommandeActionneurFrein", rtmaps.types.TYPE_BOOL)
', "AttributeError: module 'rtmaps.types' has no attribute 'TYPE_BOOL'
"]
2023/03/30 13:12:19 646103	INFO [python_manager.cpp->PythonManager::ProcessRTMapsAction:210]	Exiting now! All went well.
