		g3log created log at: Thu Mar 09 13:42:54 2023
		LOG format: [YYYY/MM/DD hh:mm:ss uuu* LEVEL FILE->FUNCTION:LINE] messagen
		(uuu*: microseconds fractions of the seconds value)

2023/03/09 13:42:54 312240	INFO [python_manager.cpp->PythonManager::InitializePython:127]	Initializing Python ... 
2023/03/09 13:42:54 332718	INFO [python_manager.cpp->PythonManager::InitializePython:129]	Initializing Python DONE... 
2023/03/09 13:42:54 332727	INFO [python_manager.cpp->PythonManager::InitNumpy:172]	Init numpy... 
2023/03/09 13:42:54 457022	INFO [python_manager.cpp->PythonManager::InitNumpy:174]	Init numpy DONE... 
2023/03/09 13:45:09 162850	INFO [python_manager.cpp->PythonManager::Death:637]	Death()
2023/03/09 13:50:19 314082	WARNING [python_manager.cpp->PythonManager::CheckForErrors:745]	Error, traceback : ['Traceback (most recent call last):
', '  File "C:/Users/user/OneDrive - ESTACA/Documents/GitHub/ESTADRIVE_23/Main_Perception/PythonBridges\\Yolo_RTMaps2.py", line 137, in Core
    filteredIds(CmrObject)
', "NameError: name 'CmrObject' is not defined
"]
2023/03/09 13:50:19 335597	INFO [python_manager.cpp->PythonManager::Death:637]	Death()
2023/03/09 13:50:50 648560	WARNING [python_manager.cpp->PythonManager::CheckForErrors:745]	Error, traceback : ['Traceback (most recent call last):
', '  File "C:/Users/user/OneDrive - ESTACA/Documents/GitHub/ESTADRIVE_23/Main_Perception/PythonBridges\\Yolo_RTMaps2.py", line 137, in Core
    CmrObject = filteredIds(CmrObject)
', "UnboundLocalError: local variable 'CmrObject' referenced before assignment
"]
2023/03/09 13:50:50 648985	INFO [python_manager.cpp->PythonManager::Death:637]	Death()
2023/03/09 13:51:06 874574	WARNING [python_manager.cpp->PythonManager::CheckForErrors:745]	Error, traceback : ['Traceback (most recent call last):
', '  File "C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python38\\Lib\\imp.py", line 314, in reload
    return importlib.reload(module)
', '  File "C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python38\\Lib\\importlib\\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
', '  File "<frozen importlib._bootstrap>", line 604, in _exec
', '  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
', '  File "<frozen importlib._bootstrap_external>", line 916, in get_code
', '  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
', '  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
', '  File "C:/Users/user/OneDrive - ESTACA/Documents/GitHub/ESTADRIVE_23/Main_Perception/PythonBridges\\Yolo_RTMaps2.py", line 47
', '    return input
', '    ^
', "SyntaxError: 'return' outside function
"]
2023/03/09 13:51:11 280990	WARNING [python_manager.cpp->PythonManager::CheckForErrors:745]	Error, traceback : ['Traceback (most recent call last):
', '  File "C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python38\\Lib\\imp.py", line 314, in reload
    return importlib.reload(module)
', '  File "C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python38\\Lib\\importlib\\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
', '  File "<frozen importlib._bootstrap>", line 604, in _exec
', '  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
', '  File "<frozen importlib._bootstrap_external>", line 916, in get_code
', '  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
', '  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
', '  File "C:/Users/user/OneDrive - ESTACA/Documents/GitHub/ESTADRIVE_23/Main_Perception/PythonBridges\\Yolo_RTMaps2.py", line 47
', '    return input
', '    ^
', "SyntaxError: 'return' outside function
"]
2023/03/09 13:51:11 327462	WARNING [python_manager.cpp->PythonManager::CheckForErrors:745]	Error, traceback : ['Traceback (most recent call last):
', '  File "C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python38\\Lib\\imp.py", line 314, in reload
    return importlib.reload(module)
', '  File "C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python38\\Lib\\importlib\\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
', '  File "<frozen importlib._bootstrap>", line 604, in _exec
', '  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
', '  File "<frozen importlib._bootstrap_external>", line 916, in get_code
', '  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
', '  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
', '  File "C:/Users/user/OneDrive - ESTACA/Documents/GitHub/ESTADRIVE_23/Main_Perception/PythonBridges\\Yolo_RTMaps2.py", line 47
', '    return input
', '    ^
', "SyntaxError: 'return' outside function
"]
2023/03/09 13:51:13 720410	WARNING [python_manager.cpp->PythonManager::Dynamic:563]	PythonManager::Dynamic() PYTHON_ERROR
2023/03/09 13:51:13 720417	WARNING [python_manager.cpp->PythonManager::Birth:587]	PythonManager::Birth() PYTHON_ERROR
2023/03/09 13:54:38 148320

***** FATAL EXCEPTION RECEIVED ******* 

***** Vectored Exception Handler: Received fatal exception EXCEPTION_ACCESS_VIOLATION	PID: 12992

*******	STACKDUMP *******
stack dump [0]	 
stack dump [1]	 
stack dump [2]	 
stack dump [3]	 
stack dump [4]	 
stack dump [5]	 
stack dump [6]	 
stack dump [7]	 
stack dump [8]	 
stack dump [9]	 
stack dump [10]	 
stack dump [11]	 
stack dump [12]	 
stack dump [13]	 
stack dump [14]	 
stack dump [15]	 
stack dump [16]	 
stack dump [17]	 
stack dump [18]	 
stack dump [19]	 
stack dump [20]	 
stack dump [21]	 
stack dump [22]	 
stack dump [23]	 
stack dump [24]	 
stack dump [25]	 
stack dump [26]	 
stack dump [27]	 
stack dump [28]	 
stack dump [29]	 
stack dump [30]	 
stack dump [31]	 
stack dump [32]	 
stack dump [33]	 
stack dump [34]	 
stack dump [35]	 
stack dump [36]	 
stack dump [37]	 
stack dump [38]	 
stack dump [39]	 
stack dump [40]	 
stack dump [41]	 
stack dump [42]	 
stack dump [43]	 
stack dump [44]	 
stack dump [45]	 
stack dump [46]	 
stack dump [47]	 
stack dump [48]	 
stack dump [49]	 
stack dump [50]	 
stack dump [51]	 
stack dump [52]	 
stack dump [53]	 
stack dump [54]	 
stack dump [55]	 
stack dump [56]	 
stack dump [57]	 
stack dump [58]	 
stack dump [59]	 
stack dump [60]	 
stack dump [61]	 
stack dump [62]	 
stack dump [63]	 

Exiting after fatal event  (FATAL_EXCEPTION). Fatal type:  EXCEPTION_ACCESS_VIOLATION
Log content flushed sucessfully to sink


g3log g3FileSink shutdown at: 13:54:38 148755
