		g3log created log at: Thu Mar 09 13:08:55 2023
		LOG format: [YYYY/MM/DD hh:mm:ss uuu* LEVEL FILE->FUNCTION:LINE] messagen
		(uuu*: microseconds fractions of the seconds value)

2023/03/09 13:08:55 305888	INFO [python_manager.cpp->PythonManager::InitializePython:127]	Initializing Python ... 
2023/03/09 13:08:55 325600	INFO [python_manager.cpp->PythonManager::InitializePython:129]	Initializing Python DONE... 
2023/03/09 13:08:55 325608	INFO [python_manager.cpp->PythonManager::InitNumpy:172]	Init numpy... 
2023/03/09 13:08:55 435545	INFO [python_manager.cpp->PythonManager::InitNumpy:174]	Init numpy DONE... 
2023/03/09 13:26:01 525785	INFO [python_manager.cpp->PythonManager::Death:637]	Death()
2023/03/09 13:51:06 874575	WARNING [python_manager.cpp->PythonManager::CheckForErrors:745]	Error, traceback : ['Traceback (most recent call last):
', '  File "C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python38\\Lib\\imp.py", line 314, in reload
    return importlib.reload(module)
', '  File "C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python38\\Lib\\importlib\\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
', '  File "<frozen importlib._bootstrap>", line 604, in _exec
', '  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
', '  File "<frozen importlib._bootstrap_external>", line 916, in get_code
', '  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
', '  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
', '  File "C:/Users/user/OneDrive - ESTACA/Documents/GitHub/ESTADRIVE_23/Main_Perception/PythonBridges\\Yolo_RTMaps2.py", line 47
', '    return input
', '    ^
', "SyntaxError: 'return' outside function
"]
2023/03/09 13:51:11 280990	WARNING [python_manager.cpp->PythonManager::CheckForErrors:745]	Error, traceback : ['Traceback (most recent call last):
', '  File "C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python38\\Lib\\imp.py", line 314, in reload
    return importlib.reload(module)
', '  File "C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python38\\Lib\\importlib\\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
', '  File "<frozen importlib._bootstrap>", line 604, in _exec
', '  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
', '  File "<frozen importlib._bootstrap_external>", line 916, in get_code
', '  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
', '  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
', '  File "C:/Users/user/OneDrive - ESTACA/Documents/GitHub/ESTADRIVE_23/Main_Perception/PythonBridges\\Yolo_RTMaps2.py", line 47
', '    return input
', '    ^
', "SyntaxError: 'return' outside function
"]
2023/03/09 13:51:11 327406	WARNING [python_manager.cpp->PythonManager::CheckForErrors:745]	Error, traceback : ['Traceback (most recent call last):
', '  File "C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python38\\Lib\\imp.py", line 314, in reload
    return importlib.reload(module)
', '  File "C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python38\\Lib\\importlib\\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
', '  File "<frozen importlib._bootstrap>", line 604, in _exec
', '  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
', '  File "<frozen importlib._bootstrap_external>", line 916, in get_code
', '  File "<frozen importlib._bootstrap_external>", line 846, in source_to_code
', '  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
', '  File "C:/Users/user/OneDrive - ESTACA/Documents/GitHub/ESTADRIVE_23/Main_Perception/PythonBridges\\Yolo_RTMaps2.py", line 47
', '    return input
', '    ^
', "SyntaxError: 'return' outside function
"]
2023/03/09 13:53:43 477293	WARNING [python_manager.cpp->PythonManager::CheckForErrors:754]	Error : AttributeError("'cv2.GArrayT' object has no attribute 'Dynamic'")
2023/03/09 13:55:38 231377	INFO [python_manager.cpp->PythonManager::ProcessRTMapsAction:210]	Exiting now! All went well.
